# Generated by Django 4.1 on 2022-08-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consultations',
            fields=[
                ('consultation_id', models.SmallAutoField(db_column='Consultation_ID', editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Consultations',
                'db_table': 'Consultations',
            },
        ),
    ]
