# Generated by Django 4.1 on 2022-09-28 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinics',
            fields=[
                ('clinic_id', models.SmallAutoField(db_column='clinic_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Clinics',
                'db_table': 'Clinic',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.SmallAutoField(db_column='report_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Names', editable=False, max_length=100)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('subject', models.CharField(blank=True, db_column='subject', max_length=500, null=True)),
                ('message', models.TextField(blank=True, db_column='message', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.SmallAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('phonenum', models.CharField(blank=True, db_column='PhoneNum', max_length=30, null=True)),
                ('role', models.CharField(choices=[('Patient', 'Patient'), ('Clinic', 'Clinic'), ('Pharmacist', 'Pharmacist')], default='Patient', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_relative', models.BooleanField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('specialisation', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('pharmacy_id', models.SmallAutoField(db_column='pharmacy_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'Pharmacy',
            },
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('consultation_id', models.SmallAutoField(db_column='Consultation_ID', editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Datetime', null=True)),
                ('time', models.TimeField(blank=True, db_column='time', null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Served', 'Served'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Pending')], default='Pending', max_length=255)),
                ('clinic_report', models.TextField(blank=True, max_length=1000, null=True)),
                ('clinic_report_date', models.DateTimeField(blank=True, db_column='report_date', null=True)),
                ('prescription', models.CharField(blank=True, max_length=500, null=True)),
                ('bill_pharmacy', models.BigIntegerField(blank=True, null=True)),
                ('pin_pharmacy', models.BooleanField(blank=True, default=False, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.clinics')),
                ('pharmacy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.pharmacy')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Consultations',
                'db_table': 'Consultations',
            },
        ),
        migrations.AddField(
            model_name='clinics',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
