# Generated by Django 4.1 on 2022-09-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='bill',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='clinic_report_date',
            field=models.DateTimeField(blank=True, db_column='report_date', null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='final_bill',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
