# Generated by Django 4.1 on 2022-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_consultations_bill_consultations_clinic_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='status',
            field=models.CharField(choices=[('Served', 'Served'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Pending')], default='Patient', max_length=255),
        ),
    ]
