# Generated by Django 4.1 on 2022-09-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_consultations_clinic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationsReport',
            fields=[
                ('report_id', models.SmallAutoField(db_column='report_id', editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, db_column='comment', max_length=100)),
                ('prescription', models.TextField(blank=True, db_column='prescription', max_length=100)),
                ('consultation_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.consultations')),
            ],
            options={
                'verbose_name_plural': 'ConsultationsReports',
                'db_table': 'ConsultationsReport',
            },
        ),
    ]
