# Generated by Django 4.1 on 2022-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_consultationsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_relative',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
