# Generated by Django 4.1 on 2022-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_consultations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
