# Generated by Django 4.1 on 2022-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
