# Generated by Django 4.1 on 2022-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_clinics_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
