# Generated by Django 4.1 on 2022-09-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_consultations_pharmacy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultations',
            old_name='bill',
            new_name='bill_clinic',
        ),
        migrations.RenameField(
            model_name='consultations',
            old_name='final_bill',
            new_name='paid_clinic',
        ),
    ]
