# Generated by Django 4.1 on 2022-09-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_rename_bill_consultations_bill_clinic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultations',
            old_name='bill_clinic',
            new_name='bill_pharmacy',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='paid_clinic',
        ),
        migrations.AlterField(
            model_name='consultations',
            name='status',
            field=models.CharField(choices=[('Served', 'Served'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Pending')], default='Pending', max_length=255),
        ),
    ]
