# Generated by Django 4.1 on 2022-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_rename_clinic_id_consultations_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(blank=True, db_column='Role', null=True),
        ),
    ]
