# Generated by Django 4.1 on 2022-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=40, null=True),
        ),
    ]
