# Generated by Django 4.1 on 2022-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_rename_bill_clinic_consultations_bill_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='pin_clinic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='pin_pharmacy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
