# Generated by Django 4.1 on 2022-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_consultations_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.SmallAutoField(db_column='report_id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Names', editable=False, max_length=100)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('subject', models.CharField(blank=True, db_column='subject', max_length=500, null=True)),
                ('message', models.TextField(blank=True, db_column='message', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contacts',
            },
        ),
    ]
