# Generated by Django 4.1 on 2022-09-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mail_verified',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Patient', 'patient'), ('Clinic', 'clinic'), ('Pharmacist', 'pharmacist')], default='patient', max_length=255),
        ),
    ]
