# Generated by Django 4.1 on 2022-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_remove_users_mail_verified_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='Kigali, Rwanda', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='Kigali', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
