# Generated by Django 4.1 on 2022-09-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_consultations_clinic_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationsReport',
        ),
    ]
